sonar.projectKey=carbonio-admin-console-ui
sonar.projectName=Admin UI monorepo

# Define the modules
sonar.modules=admin-ui-bootstrapper,admin-ui-console

# Properties for the 'admin-ui-bootstrapper' module
admin-ui-bootstrapper.sonar.projectKey=carbonio-admin-console-ui:admin-ui-bootstrapper
admin-ui-bootstrapper.sonar.projectBaseDir=apps/admin-ui-bootstrapper
admin-ui-bootstrapper.sonar.sources=.
admin-ui-bootstrapper.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Properties for the 'admin-ui-console' module
admin-ui-console.sonar.projectKey=carbonio-admin-console-ui:admin-ui-console
admin-ui-console.sonar.projectBaseDir=apps/admin-ui-console
admin-ui-console.sonar.sources=.
admin-ui-console.sonar.javascript.lcov.reportPaths=coverage/lcov.info
