sonar.projectKey=carbonio-admin-console-ui
sonar.projectName=Admin UI Console

sonar.sources=apps/admin-ui-console/src/
sonar.exclusions=apps/admin-ui-bootstrapper/**,**/*.test.*.*,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/node_modules/**

sonar.test.inclusions=**/*.test.**,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/tests/**
sonar.coverage.exclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/*.d.ts,**/jest-*
sonar.cpd.exclusions=**/*.test.*
