sonar.projectKey=carbonio-admin-console-ui
sonar.projectName=Admin UI monorepo

# Define the modules
sonar.modules=admin-ui-bootstrap,admin-ui-console,admin-ui-cos,admin-ui-sdk

# Properties for the 'admin-ui-bootstrap' module
admin-ui-bootstrap.sonar.projectKey=carbonio-admin-console-ui:admin-ui-bootstrap
admin-ui-bootstrap.sonar.projectBaseDir=apps/admin-ui-bootstrap
admin-ui-bootstrap.sonar.sources=src/
admin-ui-bootstrap.sonar.typescript.tsconfigPaths=tsconfig.json
admin-ui-bootstrap.sonar.tests=src
admin-ui-bootstrap.sonar.test.inclusions=**/*.test.**,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/tests/**
admin-ui-bootstrap.sonar.exclusions=**/*.test.*,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/node_modules/**,pnpm*
admin-ui-bootstrap.sonar.cpd.exclusions=**/*.test.*
admin-ui-bootstrap.sonar.javascript.lcov.reportPaths=coverage/lcov.info
admin-ui-bootstrap.sonar.coverage.exclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/*.d.ts

# Properties for the 'admin-ui-console' module
admin-ui-console.sonar.projectKey=carbonio-admin-console-ui:admin-ui-console
admin-ui-console.sonar.projectBaseDir=apps/admin-ui-console
admin-ui-console.sonar.sources=src/
admin-ui-console.sonar.typescript.tsconfigPaths=tsconfig.json
admin-ui-console.sonar.tests=src/
admin-ui-console.sonar.test.inclusions=**/*.test.**,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/tests/**
admin-ui-console.sonar.exclusions=**/*.test.*,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/node_modules/**,pnpm*
admin-ui-console.sonar.cpd.exclusions=**/*.test.*
admin-ui-console.sonar.javascript.lcov.reportPaths=coverage/lcov.info
admin-ui-console.coverage.exclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/*.d.ts

# Properties for the 'admin-ui-cos' module
admin-ui-cos.sonar.projectKey=carbonio-admin-console-ui:admin-ui-cos
admin-ui-cos.sonar.projectBaseDir=apps/admin-ui-cos
admin-ui-cos.sonar.sources=src/
admin-ui-cos.sonar.typescript.tsconfigPaths=tsconfig.json
admin-ui-cos.sonar.tests=src/
admin-ui-cos.sonar.test.inclusions=**/*.test.**,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/tests/**
admin-ui-cos.sonar.exclusions=**/*.test.*,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/node_modules/**,pnpm*
admin-ui-cos.sonar.cpd.exclusions=**/*.test.*
admin-ui-cos.sonar.javascript.lcov.reportPaths=coverage/lcov.info
admin-ui-cos.coverage.exclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/*.d.ts

# Corrected properties for the 'admin-ui-sdk' module
admin-ui-sdk.sonar.projectKey=carbonio-admin-console-ui:admin-ui-sdk
admin-ui-sdk.sonar.projectBaseDir=packages/sdk
admin-ui-sdk.sonar.sources=scripts/
admin-ui-sdk.sonar.exclusions=**/*.test.*,**/mocks/**/*,**/test*.*.ts*,**/mock*.ts*,**/types/*,**/node_modules/**,pnpm*