sonar.projectKey=admin-ui-console
sonar.projectName=Admin UI Console

sonar.sources=apps/admin-ui-console/src/
sonar.exclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/node_modules/**

sonar.tests=apps/admin-ui-console/src/
sonar.test.inclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/tests/**
sonar.coverage.exclusions=**/*.test.*,**/mocks/**/*,**/test*.ts*,**/mock*.ts*,**/types/*,**/*.d.ts,**/jest-*
sonar.cpd.exclusions=**/*.test.*
