/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const optimizeDepsInclude = [
	'@zextras/carbonio-design-system',
	'i18next',
	'react-i18next',
	'react-router-dom',
	'ua-parser-js',
	'@tinymce/tinymce-react',
	'i18next-http-backend',
	'@sentry/browser',
	// TinyMCE plugins
	'tinymce/tinymce',
	'tinymce/models/dom',
	'tinymce/themes/silver',
	'tinymce/icons/default',
	'tinymce/plugins/advlist',
	'tinymce/plugins/anchor',
	'tinymce/plugins/autolink',
	'tinymce/plugins/autoresize',
	'tinymce/plugins/charmap',
	'tinymce/plugins/code',
	'tinymce/plugins/directionality',
	'tinymce/plugins/fullscreen',
	'tinymce/plugins/help',
	'tinymce/plugins/image',
	'tinymce/plugins/insertdatetime',
	'tinymce/plugins/link',
	'tinymce/plugins/lists',
	'tinymce/plugins/media',
	'tinymce/plugins/preview',
	'tinymce/plugins/quickbars',
	'tinymce/plugins/searchreplace',
	'tinymce/plugins/table',
	'tinymce/plugins/visualblocks',
	'tinymce/plugins/wordcount',
	// date-fns locales
	'date-fns/locale/zh-CN',
	'date-fns/locale/nl',
	'date-fns/locale/en-US',
	'date-fns/locale/de',
	'date-fns/locale/hi',
	'date-fns/locale/hu',
	'date-fns/locale/it',
	'date-fns/locale/ja',
	'date-fns/locale/pt',
	'date-fns/locale/pl',
	'date-fns/locale/ro',
	'date-fns/locale/ru',
	'date-fns/locale/es',
	'date-fns/locale/th',
	'date-fns/locale/tr',
	'date-fns/locale/fr',
	'date-fns/locale/vi',
	'date-fns/locale/bs',
	'date-fns/locale/sl'
];
