/*
 * SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import type { ColumnFiltersState, GroupingState, RowSelectionState } from '@tanstack/react-table';
import {
	Button,
	createDataTableColumnHelper,
	DataTable,
	DataTableColumnVisibility,
	DataTableGlobalFilter,
	DataTablePagination,
	type IconName,
	ModalOverlay,
	NotificationDetail,
	Select,
} from '@zextras/ui-components';
import {
	type Notification,
	useAllNotifications,
	useReadUnreadNotification,
	useSnackbar,
} from '@zextras/ui-shared';
import { format } from 'date-fns';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';

import styles from './dashboard-data-table-showcase.module.css';

const columnHelper = createDataTableColumnHelper<Notification>();

const SHOWCASE_PAGE_SIZE = 5;

const LEVEL_ICONS: Record<string, IconName> = {
	Error: 'CloseCircleOutline',
	Warning: 'AlertTriangleOutline',
	Information: 'InfoOutline',
};

const NOTIFICATION_ALL = 'All';

const HOUR = 3_600_000;

function buildDemoNotifications(): Array<Notification> {
	const levels = ['Information', 'Warning', 'Error'];
	const servers = ['mailstore1.example.com', 'mailstore2.example.com', 'ldap1.example.com'];
	const subjects = [
		'Mailbox quota exceeded',
		'Service restarted',
		'Certificate expiring soon',
		'Backup completed',
		'Antivirus definitions updated',
		'LDAP replication lag',
		'MTA queue backlog',
		'Account provisioned',
		'Domain alias added',
		'Index snapshot created',
		'Proxy health check failed',
		'Retention policy applied',
		'Archive migration finished',
		'Server statistics collected',
	];
	const now = Date.now();
	return subjects.map((subject, index) => ({
		ack: index % 3 === 0,
		date: now - index * HOUR,
		group: 'system',
		id: `demo-${index + 1}`,
		level: levels[index % levels.length] ?? 'Information',
		operationId: `op-${index + 1}`,
		server: servers[index % servers.length] ?? servers[0],
		subject,
		text: `${subject} — autogenerated showcase row ${index + 1}`,
	}));
}

const DEMO_NOTIFICATIONS = buildDemoNotifications();

export const DashboardDataTableShowcase = () => {
	const [t] = useTranslation();
	const createSnackbar = useSnackbar();
	const { data: notificationList = [], isPending } = useAllNotifications();
	const readUnreadMutation = useReadUnreadNotification();

	const [rowSelection, setRowSelection] = useState<RowSelectionState>({});
	const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
	const [grouping, setGrouping] = useState<GroupingState>([]);
	const [selectedNotificationId, setSelectedNotificationId] = useState<string | null>(null);

	const data = notificationList.length > 0 ? notificationList : DEMO_NOTIFICATIONS;
	const selectedCount = Object.keys(rowSelection).length;
	const selectedNotification = data.find((item) => item.id === selectedNotificationId) ?? null;

	function copyNotificationOperation(notificationSelected: Notification): void {
		const notificationItem = `
			${t('label.date', 'Date')} : ${format(notificationSelected?.date, 'dd-MM-yyyy - HH:mm a')} \n
			${t('label.type', 'Type')} : ${notificationSelected?.level} \n
			${t('label.what_inside', "What's inside?")} : ${notificationSelected?.subject} \n
			${t('label.content', 'Content')} : ${notificationSelected?.text}
		`;
		navigator.clipboard.writeText(notificationItem);
		createSnackbar({
			key: 'success',
			severity: 'success',
			label: t(
				'notification.copy_notification_successfully',
				'Notification copied successfully',
			),
			autoHideTimeout: 3000,
			hideButton: true,
			replace: true,
		});
	}
	const columns = columnHelper.columns([
		columnHelper.accessor('subject', {
			header: t('label.what_inside', "What's inside?"),
			size: 260,
			cell: ({ row, getValue }) => (
				<span className={row.original.ack ? styles.read : styles.unread}>{getValue()}</span>
			),
			footer: ({ table }) =>
				`${t('label.total', 'Total')}: ${table.getFilteredRowModel().rows.length}`,
		}),
		columnHelper.accessor('level', {
			header: t('label.type', 'Type'),
			size: 140,
			filterFn: 'equalsString',
			cell: ({ getValue }) => {
				const level = getValue();
				return (
					<span className={styles.levelCell}>
						<ds-icon icon={LEVEL_ICONS[level] ?? 'InfoOutline'} size="small" />
						{level}
					</span>
				);
			},
		}),
		columnHelper.accessor('server', {
			header: t('label.server', 'Server'),
			size: 200,
		}),
		columnHelper.accessor('date', {
			header: t('label.date', 'Date'),
			size: 190,
			cell: ({ getValue }) => format(getValue(), 'dd-MM-yyyy - HH:mm a'),
		}),
		columnHelper.accessor('text', {
			header: t('label.content', 'Content'),
		}),
	]);

	return (
		<div className={styles.root}>
			<div className={styles.header}>
				<div className={styles.titleRow}>
					<div className={styles.icon}>
						<ds-icon
							icon="ListOutline"
							size="large"
							aria-label={t('dashboard.new_table_showcase', 'New table (showcase)')}
						/>
					</div>
					<ds-text as="strong" size="medium" color="gray0" weight="bold">
						{t('dashboard.new_table_showcase', 'New table (showcase)')}
					</ds-text>
				</div>
				<ds-text as="span" size="small" color="gray1" className={styles.subtitle}>
					{t(
						'dashboard.new_table_showcase_subtitle',
						'Same data as the notifications table above, rendered with the new TanStack-based DataTable: selection, sorting, global and column filters, pagination, grouping, pinning, resizing and column visibility',
					)}
				</ds-text>
			</div>
			<div className={styles.tableWrap}>
				<DataTable
					data={data}
					columns={columns}
					isLoading={isPending && notificationList.length === 0}
					enableRowSelection
					enableSorting
					enableGlobalFilter
					enableColumnFilters
					enablePagination
					enableExpanding
					enableGrouping
					enableColumnResizing
					enableColumnVisibility
					enableColumnPinning
					enableRowPinning
					onRowClick={(row) => {
						setSelectedNotificationId(row.id);
						if (!row.ack) {
							readUnreadMutation.mutate({ notification: row, showMessage: false });
						}
					}}
					state={{ rowSelection, columnFilters, grouping }}
					onRowSelectionChange={setRowSelection}
					onColumnFiltersChange={setColumnFilters}
					onGroupingChange={setGrouping}
					initialState={{
						pagination: { pageIndex: 0, pageSize: SHOWCASE_PAGE_SIZE },
						columnPinning: { start: ['subject'], end: [] },
					}}
					toolbar={
						<div className={styles.toolbarRow}>
							<DataTableGlobalFilter className={styles.searchFilter} />
							<Select
								className={styles.levelFilter}
								items={[
									{ label: t('notification.all', 'ALL'), value: NOTIFICATION_ALL },
									{ label: t('notification.information', 'INFORMATION'), value: 'Information' },
									{ label: t('notification.warning', 'WARNING'), value: 'Warning' },
									{ label: t('notification.error', 'ERROR'), value: 'Error' },
								]}
								defaultSelection={{
									label: t('notification.all', 'ALL'),
									value: NOTIFICATION_ALL,
								}}
								background="gray5"
								showCheckbox={false}
								itemTextSize="medium"
								aria-label={t('label.filter_by_type', 'Filter by type')}
								onChange={(value) => {
									setColumnFilters(
										value && value !== NOTIFICATION_ALL
											? [{ id: 'level', value }]
											: [],
									);
								}}
							/>
							<Button
								type="ghost"
								color="primary"
								size="medium"
								label={t('label.group_by_type', 'Group by type')}
								onClick={() => {
									setGrouping(grouping.length > 0 ? [] : ['level']);
								}}
							/>
							<div className={styles.toolbarSpacer} />
							{selectedCount > 0 && (
								<span className={styles.selectedChip}>
									{t('label.n_selected', '{{count}} selected', { count: selectedCount })}
								</span>
							)}
							<DataTableColumnVisibility />
							<DataTablePagination />
						</div>
					}
				/>
			</div>
			{selectedNotification && (
				<ModalOverlay open={selectedNotification != null}>
					<NotificationDetail
						notification={selectedNotification}
						setShowNotificationDetail={(open: boolean) => {
							if (!open) {
								setSelectedNotificationId(null);
							}
						}}
						copyNotificationOperation={copyNotificationOperation}
						markAsReadUnread={(notification: Notification) => {
							readUnreadMutation.mutate({ notification });
						}}
						isRequestInProgress={readUnreadMutation.isPending}
					/>
				</ModalOverlay>
			)}
		</div>
	);
};
