/*
 * SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
export const accountDetail = {
	zimbraPrefCalendarReminderMobile: '15',
	zimbraPrefIMLogChats: 'true',
	zimbraDeviceLockWhenInactive: '30',
	zimbraPrefFileSharingApplication: 'zimbra',
	zimbraDataSourceTotalQuota: '1000',
	zimbraPrefCalendarWorkingHours: '08:00-17:00',
	zimbraFeatureOutOfOfficeReplyEnabled: 'true',
	zimbraPrefCalendarViewTimeInterval: '30',
	zimbraPrefDefaultCalendarId: 'primary',
	carbonioFeatureFilesAppEnabled: 'true',
	zimbraFeatureZXDesktopEnabled: 'true',
	zimbraPrefComposeFormat: 'html',
	zimbraPrefZmgPushNotificationEnabled: 'true',
	zimbraPrefDisplayTimeInMailList: '12',
	zimbraPrefIMNotifyStatus: 'true',
	zimbraPrefLocale: 'en_US',
	zimbraQuotaWarnPercent: '80',
	zimbraPrefIMReportIdle: 'true',
	zimbraMailHost: 'mail.example.com',
	zimbraFeatureMailForwardingEnabled: 'true',
	zimbraPrefSaveToSent: 'true',
	zimbraPrefDisplayExternalImages: 'true',
	zimbraPrefOutOfOfficeCacheDuration: '30',
	zimbraPrefConvReadingPaneLocation: 'bottom',
	zimbraPrefShowSearchString: 'true',
	zimbraInterceptSubject: 'true',
	zimbraMailTrustedSenderListMaxNumEntries: '100',
	zimbraPrefMailSelectAfterDelete: 'true',
	displayName: 'John Doe',
	zimbraPrefAppleIcalDelegationEnabled: 'true',
	zimbraDataSourceQuota: '500',
	uid: 'johndoe',
	zimbraPrefHtmlEditorDefaultFontFamily: 'Arial',
	zimbraMobilePolicyMinDevicePasswordComplexCharacters: '8',
	zimbraPrefConvShowCalendar: 'true',
	zimbraRevokeAppSpecificPasswordsOnPasswordChange: 'true',
	zimbraZimletUserPropertiesMaxNumEntries: '100',
	zimbraFeatureSMIMEEnabled: 'true',
	zimbraPrefCalendarShowPastDueReminders: 'true',
	zimbraMobilePolicyAllowPOPIMAPEmail: 'true',
	zimbraDataSourceMinPollingInterval: '1',
	zimbraMobilePolicyRequireSignedSMIMEMessages: 'true',
	zimbraPrefWarnOnExit: 'true',
	zimbraFeatureMobileGatewayEnabled: 'true',
	cn: 'John Doe',
	zimbraFeaturePriorityInboxEnabled: 'true',
	zimbraPrefReadingPaneEnabled: 'true',
	zimbraSpamApplyUserFilters: 'true',
	zimbraFeatureBriefcaseSpreadsheetEnabled: 'true',
	zimbraFeatureAddressVerificationExpiry: '30',
	zimbraQuotaWarnInterval: '1',
	zimbraMobilePolicyMaxEmailBodyTruncationSize: '1000',
	zimbraMobileMetadataMaxSizeEnabled: 'true',
	zimbraPrefIMToasterEnabled: 'true',
	zimbraPrefOutOfOfficeStatusAlertOnLogin: 'true',
	zimbraFeatureMailPriorityEnabled: 'true',
	zimbraPrefAutocompleteAddressBubblesEnabled: 'true',
	zimbraFreebusyExchangeCachedInterval: '30',
	zimbraFeatureManageZimlets: 'true',
	zimbraPasswordMinNumericChars: '8',
	zimbraWebClientShowOfflineLink: 'true',
	zimbraMobileSmartForwardRFC822Enabled: 'true',
	zimbraPrefContactsInitialView: 'list',
	zimbraFeatureCalendarEnabled: 'true',
	zimbraMailBlacklistMaxNumEntries: '100',
	carbonioFeatureMailsAppEnabled: 'true',
	zimbraPrefVoiceItemsPerPage: '10',
	zimbraMobilePolicyAllowRemoteDesktop: 'true',
	zimbraFeatureDiscardInFiltersEnabled: 'true',
	zimbraFeatureTrustedDevicesEnabled: 'true',
	zimbraMobilePolicyPasswordRecoveryEnabled: 'true',
	zimbraMailHighlightObjectsMaxSize: '1000',
	zimbraPrefMailToasterEnabled: 'true',
	zimbraFileAndroidCrashReportingEnabled: 'true',
	zimbraPrefForwardReplyInOriginalFormat: 'true',
	zimbraFeatureWebSearchEnabled: 'true',
	zimbraPrefBriefcaseReadingPaneLocation: 'bottom',
	zimbraPrefContactsPerPage: '50',
	zimbraPrefMarkMsgRead: 'true',
	zimbraPrefMessageIdDedupingEnabled: 'true',
	zimbraAccountStatus: 'active',
	zimbraPrefCalendarApptReminderWarningTime: '15',
	zimbraPrefCalendarReminderYMessenger: 'true',
	zimbraSieveRejectMailEnabled: 'false',
	zimbraPrefDeleteInviteOnReply: 'true',
	zimbraPrefCalendarDefaultApptDuration: '60',
	zimbraPasswordBlockCommonEnabled: 'true',
	zimbraPrefCalendarDayHourStart: '8',
	zimbraMaxVoiceItemsPerPage: '20',
	zimbraPrefPop3DeleteOption: 'true',
	zimbraDataSourceMaxNumEntries: '1000',
	zimbraImapEnabled: 'true',
	zimbraFeatureViewInHtmlEnabled: 'true',
	zimbraCalendarMaxRevisions: '10',
	zimbraPrefTabInEditorEnabled: 'true',
	zimbraMailSignatureMaxLength: '1000',
	zimbraPrefCalendarAutoAddInvites: 'true',
	zimbraPasswordLockoutSuppressionCacheSize: '10',
	zimbraCommunityUsernameMapping: 'username@example.com',
	zimbraFeatureSignaturesEnabled: 'true',
	zimbraPasswordRecoveryMaxAttempts: '5',
	zimbraPrefExternalSendersType: 'all',
	zimbraPrefContactsDisableAutocompleteOnContactGroupMembers: 'false',
	zimbraPrefIMFlashTitle: 'true',
	zimbraLogOutFromAllServers: 'true',
	carbonioFeatureChatsAppEnabled: 'true',
	zimbraPasswordLockoutMaxFailures: '5',
	zimbraCreateTimestamp: '2022-01-01T12:00:00.000Z',
	zimbraMobilePolicyDevicePasswordHistory: '5',
	zimbraMobilePolicyAllowDesktopSync: 'true',
	zimbraCommunityHomeURL: 'https://example.com',
	zimbraMobileTombstoneEnabled: 'true',
	zimbraFeatureImapDataSourceEnabled: 'true',
	zimbraFeatureModernDesktopEnabled: 'true',
	zimbraPrefSentLifetime: '30',
	zimbraFeatureSocialEnabled: 'true',
	zimbraMobilePolicyAllowUnsignedInstallationPackages: 'false',
	zimbraContactRankingTableSize: '100',
	zimbraPrefAutoCompleteQuickCompletionOnComma: 'true',
	zimbraPrefImapEnabled: 'true',
	zimbraPrefMailFlashIcon: 'true',
	zimbraPrefMailSoundsEnabled: 'true',
	zimbraAuthTokenLifetime: '3600',
	zimbraNewMailNotificationFrom: 'username@example.com',
	zimbraPrefFolderColorEnabled: 'true',
	zimbraAuthTokens: 'token1,token2,token3',
	zimbraFeatureMailSendLaterEnabled: 'true',
	zimbraPortalName: 'example',
	zimbraSieveRequireControlEnabled: 'true',
	zimbraTwoFactorAuthEnablementTokenLifetime: '3600',
	zimbraMobileSearchMimeSupportEnabled: 'true',
	zimbraMobilePolicyAllowNonProvisionableDevices: 'false',
	zimbraMailThreadingAlgorithm: 'by_subject',
	zimbraFeatureContactBackupEnabled: 'true',
	zimbraAuthTokenValidityValue: '3600',
	zimbraPrefIMSoundsEnabled: 'true',
	zimbraPrefGalAutoCompleteEnabled: 'true',
	zimbraPrefIMHideBlockedBuddies: 'true',
	zimbraPrefUseSendMsgShortcut: 'true',
	zimbraMobileOutlookSyncEnabled: 'true',
	zimbraPrefCalendarReminderSoundsEnabled: 'true',
	zimbraPrefCalendarShowDeclinedMeetings: 'true',
	zimbraDeviceAllowedPasscodeLockoutDuration: '30',
	zimbraFeatureEwsEnabled: 'true',
	zimbraFeatureContactsEnabled: 'true',
	zimbraPrefIMInstantNotify: 'true',
	zimbraFeatureComposeInNewWindowEnabled: 'true',
	zimbraPasswordMaxAge: '90',
	zimbraFeatureFlaggingEnabled: 'true',
	zimbraFeatureContactsDetailedSearchEnabled: 'true',
	zimbraPrefMailInitialSearch: 'all',
	zimbraPrefIMNotifyPresence: 'true',
	zimbraPrefMandatorySpellCheckEnabled: 'true',
	zimbraFeatureSocialFiltersEnabled: 'false',
	zimbraPrefDedupeMessagesSentToSelf: 'true',
	zimbraPrefHtmlEditorDefaultFontSize: '14pt',
	zimbraExternalShareDomainWhitelistEnabled: 'true',
	zimbraMobilePolicyAllowSMIMEEncryptionAlgorithmNegotiation: 'AES256',
	zimbraInterceptBody: 'Sample intercept body',
	zimbraIdentityMaxNumEntries: '5',
	zimbraFeatureAdminMailEnabled: 'true',
	zimbraBatchedIndexingSize: '100',
	zimbraDataSourceImportOnLogin: 'false',
	zimbraFeatureMAPIConnectorEnabled: 'true',
	zimbraFeatureTwoFactorAuthRequired: 'false',
	zimbraMailDeliveryAddress: 'user@example.com',
	zimbraMobilePolicyRequireSignedSMIMEAlgorithm: 'RSA',
	zimbraCalendarResourceDoubleBookingAllowed: 'false',
	zimbraPrefSentMailFolder: 'Sent',
	zimbraPrefCalendarApptVisibility: 'public',
	zimbraFileIOSCrashReportingEnabled: 'true',
	zimbraPrefCalendarDayHourEnd: '17:00',
	zimbraFeatureConversationsEnabled: 'true',
	zimbraPasswordLockoutFailureLifetime: '15m',
	zimbraFeatureDistributionListExpandMembersEnabled: 'false',
	zimbraPrefShowComposeDirection: 'ltr',
	zimbraPrefShowCalendarWeek: 'false',
	mail: 'user@example.com',
	zimbraFeatureImportExportFolderEnabled: 'true',
	zimbraMobilePolicyRequireDeviceEncryption: 'true',
	zimbraFreebusyExchangeCachedIntervalStart: '2d',
	zimbraMobilePolicyDeviceEncryptionEnabled: 'true',
	zimbraFileShareLifetime: '30d',
	zimbraLastLogonTimestamp: '2023-01-01T00:00:00Z',
	zimbraMobileNotificationEnabled: 'true',
	zimbraMobilePolicyMaxCalendarAgeFilter: '90d',
	zimbraPasswordMinLowerCaseChars: '1',
	zimbraPrefClientType: 'advanced',
	zimbraPrefIMAutoLogin: 'false',
	zimbraNotebookMaxRevisions: '10',
	zimbraFeaturePeopleSearchEnabled: 'true',
	zimbraPrefCalendarAlwaysShowMiniCal: 'true',
	zimbraPrefChatPlaySound: 'true',
	zimbraFeatureExternalFeedbackEnabled: 'false',
	zimbraPrefHtmlEditorDefaultFontColor: '#000000',
	zimbraMaxAppSpecificPasswords: '5',
	zimbraFeatureBriefcaseDocsEnabled: 'true',
	zimbraFilterSleepInterval: '5s',
	zimbraFeatureReadReceiptsEnabled: 'true',
	zimbraExternalSharingEnabled: 'true',
	zimbraPasswordLockoutSuppressionEnabled: 'true',
	zimbraPrefTasksReadingPaneLocation: 'right',
	zimbraPrefItemsPerVirtualPage: '50',
	zimbraSyncWindowSize: '100',
	zimbraChatHistoryEnabled: 'true',
	zimbraPrefSearchTreeOpen: 'true',
	zimbraPrefStandardClientAccessibilityMode: 'false',
	zimbraFeatureAntispamEnabled: 'true',
	zimbraPrefUseRfc2231: 'true',
	zimbraPrefCalendarNotifyDelegatedChanges: 'false',
	zimbraFeatureChangePasswordEnabled: 'true',
	zimbraPrefShowChatsFolderInMail: 'true',
	zimbraMobilePolicyMaxDevicePasswordFailedAttempts: '10',
	zimbraPrefConversationOrder: 'desc',
	zimbraDeviceFileOpenWithEnabled: 'true',
	zimbraFeatureMarkMailForwardedAsRead: 'false',
	zimbraMobilePolicyAllowSimpleDevicePassword: 'false',
	zimbraDataSourceRssPollingInterval: '5m',
	zimbraPrefIncludeSharedItemsInSearch: 'true',
	zimbraAttachmentsIndexingEnabled: 'true',
	zimbraDumpsterPurgeEnabled: 'false',
	zimbraPrefPop3Enabled: 'false',
	zimbraPasswordLockoutEnabled: 'true',
	zimbraArchiveAccountNameTemplate: 'archive@example.com',
	zimbraStandardClientCustomPrefTabsEnabled: 'true',
	zimbraTwoFactorAuthTrustedDeviceTokenLifetime: '365d',
	carbonioFeatureChatsEnabled: 'true',
	zimbraFeatureVoiceEnabled: 'false',
	zimbraPrefShowSelectionCheckbox: 'true',
	zimbraPrefDelegatedSendSaveTarget: 'Sent',
	zimbraPrefPop3IncludeSpam: 'false',
	zimbraFeatureBriefcaseSlidesEnabled: 'true',
	zimbraMobileAttachSkippedItemEnabled: 'true',
	zimbraPrefCalendarReminderFlashTitle: 'true',
	zimbraFeatureMailForwardingInFiltersEnabled: 'true',
	zimbraPrefDefaultPrintFontSize: '12pt',
	zimbraFeatureSocialcastEnabled: 'false',
	zimbraPrefMessageViewHtmlPreferred: 'true',
	zimbraPrefMailFlashTitle: 'false',
	zimbraFeatureCalendarUpsellEnabled: 'false',
	zimbraMobilePolicyAllowSMIMESoftCerts: 'true',
	zimbraMobilePolicyMaxEmailAgeFilter: '365d',
	zimbraInterceptSendHeadersOnly: 'false',
	zimbraMobileForceSamsungProtocol25: 'false',
	zimbraPrefMailPollingInterval: '5m',
	zimbraPrefFontSize: 'medium',
	zimbraId: '7779b3d9-0102-407e-aa1e-63684f1268bb',
	zimbraPrefIMLogChatsEnabled: 'true',
	zimbraPrefReplyIncludeOriginalText: 'include',
	zimbraFeatureGalSyncEnabled: 'true',
	zimbraFeatureIdentitiesEnabled: 'true',
	zimbraPrefIncludeTrashInSearch: 'true',
	zimbraPrefSharedAddrBookAutoCompleteEnabled: 'true',
	zimbraFeatureImportFolderEnabled: 'true',
	zimbraFeatureOptionsEnabled: 'true',
	zimbraFeatureAdvancedSearchEnabled: 'true',
	zimbraPrefCalendarAllowCancelEmailToSelf: 'true',
	zimbraFeatureChatEnabled: 'true',
	zimbraFeatureResetPasswordSuspensionTime: '15m',
	zimbraFeatureTasksEnabled: 'true',
	zimbraMailPurgeUseChangeDateForTrash: 'true',
	zimbraExternalAccountLifetimeAfterDisabled: '30d',
	zimbraDevicePasscodeEnabled: 'true',
	zimbraPrefCalendarAllowPublishMethodInvite: 'true',
	zimbraSieveImmutableHeaders: 'false',
	zimbraPasswordLocked: 'false',
	zimbraFeatureNewAddrBookEnabled: 'true',
	zimbraMobilePolicyRequireEncryptedSMIMEMessages: 'true',
	zimbraMobilePolicyRefreshInterval: '1h',
	zimbraFeatureAddressVerificationEnabled: 'false',
	zimbraFeatureVoiceChangePinEnabled: 'true',
	zimbraCalendarCalDavSharedFolderCacheDuration: '1d',
	zimbraPrefIMIdleStatus: 'away',
	zimbraPasswordMinAlphaChars: '1',
	zimbraMailSpamLifetime: '30d',
	zimbraPrefGroupMailBy: 'conversation',
	zimbraMailForwardingAddressMaxNumAddrs: '10',
	zimbraNewMailNotificationSubject: 'New mail notification',
	zimbraMailQuota: '1024',
	zimbraQuotaWarnMessage: 'Warning: Approaching quota',
	zimbraFeatureZimbraAssistantEnabled: 'true',
	zimbraContactAutoCompleteEmailFields: 'all',
	zimbraShowClientTOS: 'false',
	zimbraPrefCalendarAllowForwardedInvite: 'true',
	zimbraFeatureGroupCalendarEnabled: 'true',
	zimbraPrefZimletTreeOpen: 'true',
	zimbraFilterBatchSize: '100',
	zimbraArchiveAccountDateTemplate: 'YYYY-MM-DD',
	zimbraSignatureMaxNumEntries: '5',
	zimbraPrefCalendarUseQuickAdd: 'true',
	zimbraPrefComposeInNewWindow: 'true',
	zimbraAttachmentsBlocked: 'false',
	zimbraPrefGalSearchEnabled: 'true',
	zimbraPrefJunkLifetime: '30d',
	zimbraPrefSpellIgnoreAllCaps: 'false',
	sn: 'cena',
	carbonioFeatureFilesEnabled: 'true',
	zimbraFeatureManageSMIMECertificateEnabled: 'true',
	zimbraMailDumpsterLifetime: '30d',
	zimbraAppSpecificPasswordDuration: '7d',
	zimbraExportMaxDays: '30',
	zimbraPrefUseTimeZoneListInCalendar: 'true',
	zimbraCalendarKeepExceptionsOnSeriesTimeChange: 'true',
	zimbraPrefCalendarAllowedTargetsForInviteDeniedAutoReply: 'all',
	zimbraPrefOpenMailInNewWindow: 'true',
	zimbraMobilePolicyAlphanumericDevicePasswordRequired: 'true',
	zimbraAdminAuthTokenLifetime: '8h',
	zimbraFileExternalShareLifetime: '30d',
	zimbraFeatureTaggingEnabled: 'true',
	zimbraCalendarShowResourceTabs: 'true',
	zimbraMobilePolicyRequireStorageCardEncryption: 'true',
	zimbraPrefMailSignatureStyle: 'outlook',
	zimbraTwoFactorAuthLockoutMaxFailures: '5',
	zimbraMailIdleSessionTimeout: '30m',
	zimbraArchiveEnabled: 'true',
	zimbraDeviceOfflineCacheEnabled: 'true',
	zimbraPop3Enabled: 'false',
	zimbraFeatureBriefcaseZimletEnabled: 'true',
	zimbraPrefSpellIgnoreDomainNames: 'true',
	zimbraMobilePolicyAllowUnsignedApplications: 'false',
	zimbraSyncDevicesEnabled: 'true',
	zimbraPasswordLockoutDuration: '15m',
	zimbraTwoFactorAuthSecret: 'SECRET123',
	zimbraPrefImapIncludeSpam: 'false',
	zimbraTwoFactorAuthRequired: 'false',
	zimbraPrefOutOfOfficeReplyEnabled: 'true',
	zimbraFeatureTeamCalendarEnabled: 'true',
	zimbraPop3RetrievalEnabled: 'true'
};

export const domain = {
	name: 'demo.zextras.io',
	id: '142f56c1-aaf1-432b-9cfa-448e1b952cf6',
	a: [
		{
			n: 'zimbraGalAccountId',
			_content: '5b099ec4-1a40-4b98-ba2b-63525d5fc'
		},
		{
			n: 'carbonioNotificationFrom',
			_content: 'zextras@demo.zextras.io'
		},
		{
			n: 'zimbraDomainName',
			_content: 'demo.zextras.io'
		},
		{
			n: 'carbonioSearchSpecifiedDomainsByFeature',
			_content: 'abc.com'
		},
		{
			n: 'objectClass',
			_content: 'dcObject'
		},
		{
			n: 'objectClass',
			_content: 'organization'
		},
		{
			n: 'objectClass',
			_content: 'zimbraDomain'
		},
		{
			n: 'objectClass',
			_content: 'amavisAccount'
		},
		{
			n: 'carbonioNotificationRecipients',
			_content: 'zextras@demo.zextras.io'
		},
		{
			n: 'zimbraMailStatus',
			_content: 'enabled'
		},
		{
			n: 'o',
			_content: 'demo.zextras.io domain'
		},
		{
			n: 'zimbraNotes',
			_content: 'aab'
		},
		{
			n: 'zimbraPublicServiceHostname',
			_content: 'kc-dev5-u22-ce.demo.zextras.io'
		},
		{
			n: 'zimbraDomainStatus',
			_content: 'active'
		},
		{
			n: 'zimbraDomainDefaultCOSId',
			_content: '230fafd4-987b-4d2c-a4ba-fb9bc6b71f97'
		},
		{
			n: 'zimbraId',
			_content: '142f56c1-aaf1-432b-9cfa-448e1b952cf6'
		},
		{
			n: 'zimbraDomainType',
			_content: 'local'
		},
		{
			n: 'zimbraCreateTimestamp',
			_content: '20240718072455.621Z'
		},
		{
			n: 'zimbraAggregateQuotaLastUsage',
			_content: '905962776'
		},
		{
			n: 'dc',
			_content: 'demo'
		}
	]
};
