/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Plugin } from 'vite';

import { getWorkspaceRoot } from '../../../scripts/utils';
import type { AppManifest } from '../src/apps/types';

/**
 * Read app-manifest.json and extract app manifests
 */
function loadAppManifests(): Array<AppManifest> {
  const rootDir = getWorkspaceRoot();
  const manifestPath = resolve(rootDir, 'app-manifest.json');
  
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    return (manifest.apps || []).map((app: any): AppManifest => ({
      name: app.name,
      packageName: app.packageName,
      displayName: app.displayName,
      priority: app.priority ?? 99,
      icon: app.icon,
      entryPoint: app.entryPoint,
    }));
  } catch {
    return [];
  }
}

/**
 * Generate state objects for apps and appContexts
 */
function buildStateObjects(apps: Array<AppManifest>): { apps: string; appContexts: string } {
  const appsObject = apps.reduce(
    (acc, app) => ({
      ...acc,
      [app.name]: {
        description: '',
        name: app.name,
        priority: app.priority,
        type: 'carbonioAdmin',
        icon: app.icon,
        display: app.displayName,
        js_entrypoint: app.entryPoint,
      },
    }),
    {},
  );
  const appContextsObject = apps.reduce((acc, app) => ({ ...acc, [app.name]: {} }), {});

  return {
    apps: JSON.stringify(appsObject),
    appContexts: JSON.stringify(appContextsObject),
  };
}

/**
 * Generate import statement for an app
 */
function generateImportStatement(app: AppManifest, index: number): string {
  return `    const module${index} = await import('${app.packageName}');`;
}

/**
 * Generate component extraction from module
 */
function generateComponentExtraction(index: number): string {
  return `    const Component = module${index}.default;`;
}

/**
 * Generate store state update for entry point
 */
function generateEntryPointsUpdate(app: AppManifest, index: number): string {
  return `    useAppStore.setState((state) => ({
      entryPoints: {
        ...state.entryPoints,
        ['${app.name}']: module${index}.default
      }
    }));`;
}

/**
 * Generate app context mapping
 */
function generateAppContextMap(app: AppManifest): string {
  return `    appContextMap.set('${app.packageName}', APP_REGISTRY.find((a) => a.packageName === '${app.packageName}'));`;
}

/**
 * Generate success log message
 */
function generateSuccessLog(app: AppManifest): string {
  return `    console.info('%c loaded ${app.name}', 'color: white; background: #539507;padding: 4px 8px 2px 4px; font-family: sans-serif; border-radius: 12px; width: 100%');`;
}

/**
 * Generate error log message
 */
function generateErrorLog(app: AppManifest): string {
  return `    console.error('Failed to load app ${app.name}:', error);`;
}

/**
 * Generate complete try-catch block for an app
 */
function generateAppTryCatchBlock(app: AppManifest, index: number): string {
  return `  try {
${generateImportStatement(app, index)}
${generateComponentExtraction(index)}
${generateEntryPointsUpdate(app, index)}
${generateAppContextMap(app)}
${generateSuccessLog(app)}
  } catch (error) {
${generateErrorLog(app)}
  }`;
}

/**
 * Generate loadAllApps function code
 * @param apps - Array of app manifests
 * @returns Generated function code string
 */
function generateLoadAllAppsCode(apps: Array<AppManifest>): string {
  const { apps: appsStr, appContexts: appContextsStr } = buildStateObjects(apps);
  const stateInitCode = `  useAppStore.setState((state) => ({
    apps: { ...${appsStr} },
    appContexts: { ...${appContextsStr} }
  }));`;

  const lines: Array<string> = [];

  lines.push('export const APP_REGISTRY = ' + JSON.stringify(apps, null, '\t') + ';');
  lines.push('');
  lines.push('export async function loadAllApps(useAppStore, appContextMap) {');
  lines.push(stateInitCode);
  lines.push('');

  apps.forEach((app, index) => {
    const tryCatchBlock = generateAppTryCatchBlock(app, index);
    lines.push(tryCatchBlock);
    if (index < apps.length - 1) {
      lines.push('');
    }
  });

  lines.push('}');

  return lines.join('\n');
}

/**
 * Vite plugin to generate app registry module from app-manifest.json
 */
export function appRegistryPlugin(): Plugin {
  const virtualModuleId = 'virtual:app-registry';
  const resolvedVirtualModuleId = '\0' + virtualModuleId;

  return {
    name: 'app-registry',
    resolveId(id: string) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },
    load(id: string) {
      if (id === resolvedVirtualModuleId) {
        const apps = loadAppManifests();
        const functionCode = generateLoadAllAppsCode(apps);

        return `/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Auto-generated by app-registry Vite plugin
 */

${functionCode}
`;
      }
    },
  };
}
