/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Plugin } from 'vite';

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import svgr from 'vite-plugin-svgr';

import { createBootstrapRollupOptions } from '../../vite.rollup.config';

type AppManifest = {
  readonly name: string;
  readonly packageName: string;
  readonly displayName: string;
  readonly priority: number;
  readonly icon: string;
  readonly attrKey: string;
  readonly version: string;
  readonly entryPoint: string;
};

// IMPORTANT: For production, always build with NODE_ENV=production and vite build --mode production
const commitHash =
  process.env.COMMIT_HASH ||
  /* @__PURE__ */ (() => {
    try {
      return /* @__PURE__ */ require('child_process')
        .execSync('git rev-parse HEAD')
        .toString()
        .trim();
    } catch {
      return 'unknown';
    }
  })();
const packageName = 'carbonio-admin-ui';
const basePath = `/static/iris/${packageName}/${commitHash}/`;
const appsDir = join(__dirname, '../../apps');
const apps = readdirSync(appsDir).filter(
  (dir) => dir.startsWith('admin-ui-') && dir !== 'admin-ui-bootstrap',
);

const appRegistryPlugin = (): Plugin => {
  const virtualModuleId = 'virtual:app-registry';
  const resolvedVirtualModuleId = '\0' + virtualModuleId;

  return {
    name: 'app-registry',
    resolveId(id: string) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },
    load(id: string) {
      if (id === resolvedVirtualModuleId) {
        const appsDir = join(__dirname, '../../apps');
        const adminUiDirs = readdirSync(appsDir).filter(
          (dir) => dir.startsWith('admin-ui-') && dir !== 'admin-ui-bootstrap',
        );

        const apps = adminUiDirs
          .map((dir): AppManifest | null => {
            const packageJsonPath = join(appsDir, dir, 'package.json');
            try {
              const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
              const carbonio = packageJson.carbonio;

              if (carbonio && carbonio.type === 'carbonioAdmin') {
                return {
                  name: carbonio.name,
                  packageName: packageJson.name,
                  displayName: carbonio.display,
                  priority: carbonio.priority ?? 99,
                  icon: carbonio.icon,
                  attrKey: carbonio.attrKey ?? '',
                  version: packageJson.version,
                  entryPoint: packageJson.name,
                };
              }
            } catch {
              // Skip if package.json cannot be read
            }
            return null;
          })
          .filter((app): app is AppManifest => app !== null)
          .sort((a, b) => a.priority - b.priority);

        // Generate JavaScript module content (types provided via .d.ts)
        const appImports = apps.map(
          (app) =>
            `try {
    const module${apps.indexOf(app)} = await import('${app.packageName}');
    const Component = module${apps.indexOf(app)}.default;
    useAppStore.setState((state) => ({
      entryPoints: {
        ...state.entryPoints,
        ['${app.name}']: Component
      }
    }));
    appContextMap.set('${app.packageName}', APP_REGISTRY.find((a) => a.packageName === '${app.packageName}'));
    console.info('%c loaded ${app.name}', 'color: white; background: #539507;padding: 4px 8px 2px 4px; font-family: sans-serif; border-radius: 12px; width: 100%');
  } catch (error) {
    console.error('Failed to load app ${app.name}:', error);
  }`
        );

        return `/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Auto-generated by app-registry Vite plugin
 */

export const APP_REGISTRY = ${JSON.stringify(apps, null, '\t')};

export const getAppByName = (name) => APP_REGISTRY.find((app) => app.name === name);
export const getAppByPackageName = (packageName) => APP_REGISTRY.find((app) => app.packageName === packageName);

export async function loadAllApps(useAppStore, appContextMap) {
  ${appImports.join('\n\n  ')}
}
`;
      }
    },
  };
};

const getProxyTarget = (): string => {
  const target = process.env.VITE_TARGET || 'localhost';
  console.log('Proxy target:', `https://${target}:6071`);
  return `https://${target}:6071`;
};

export default defineConfig(({ mode }) => {
  const isDev = mode === 'development';
  const proxyTarget = getProxyTarget();

  return {
    plugins: [
      react({
        babel: {
          plugins: ['babel-plugin-styled-components'],
        },
      }),
      svgr({
        svgrOptions: {
          ref: true,
          svgo: false,
          titleProp: true,
          exportType: 'default',
        },
        include: '**/*.svg',
      }),
      appRegistryPlugin(),
    ],
    define: {
      COMMIT_ID: JSON.stringify(commitHash),
      BASE_PATH: JSON.stringify(isDev ? '/carbonioAdmin/' : basePath),
      'process.env.NODE_ENV': JSON.stringify(isDev ? 'development' : 'production'),
    },
    resolve: {
      alias: {
        path: 'path-browserify',
        ...apps.reduce((acc: Record<string, string>, dir: string) => {
          const packageJsonPath = join(appsDir, dir, 'package.json');
          try {
            const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
            if (packageJson.name) {
              const indexPath = join(appsDir, dir, 'src/index.ts');
              const appPath = join(appsDir, dir, 'src/app.tsx');
              acc[packageJson.name] = existsSync(indexPath) ? indexPath : appPath;
            }
          } catch {
            // Skip if package.json cannot be read
          }
          return acc;
        }, {}),
      },
      extensions: ['.mjs', '.js', '.mts', '.ts', '.jsx', '.tsx', '.json', '.d.ts'],
      dedupe: ['react', 'react-dom', 'styled-components'],
    },
    build: {
      outDir: `dist/source/${commitHash}`,
      emptyOutDir: true,
      sourcemap: isDev,
      rollupOptions: createBootstrapRollupOptions(isDev),
    },
    base: isDev ? '/carbonioAdmin/' : basePath,
    publicDir: 'assets',
    server: {
      port: 3000,
      strictPort: false,
      proxy: {
        '/carbonioAdmin/static': {
          target: proxyTarget,
          changeOrigin: true,
          secure: false,
          rewrite: (path) => path.replace(/^\/carbonioAdmin\/static/, '/static'),
          followRedirects: true,
        },
        '/service': {
          target: proxyTarget,
          changeOrigin: true,
          secure: false,
        },
        '/logout': {
          target: proxyTarget,
          changeOrigin: true,
        },
        '/zx': {
          target: proxyTarget,
          changeOrigin: true,
        },
        '/services': {
          target: proxyTarget,
          changeOrigin: true,
        },
        '/static/login': {
          target: proxyTarget,
          changeOrigin: true,
          secure: false,
        },
      },
    },
  };
});
