/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Plugin } from 'vite';

import type { AppManifest } from './src/apps/types';

/**
 * Scan apps directory and build app manifests
 * @returns Array of AppManifest sorted by priority
 */
function scanAppsDir(): Array<AppManifest> {
  const appsDir = join(__dirname, '../../apps');
  const adminUiDirs = readdirSync(appsDir).filter(
    (dir) => dir.startsWith('admin-ui-') && dir !== 'admin-ui-bootstrap',
  );

  return adminUiDirs
    .map((dir): AppManifest | null => {
      const packageJsonPath = join(appsDir, dir, 'package.json');
      try {
        const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
        const carbonio = packageJson.carbonio;

        if (carbonio && carbonio.type === 'carbonioAdmin') {
          const manifest: AppManifest = {
            name: carbonio.name,
            packageName: packageJson.name,
            displayName: carbonio.display,
            priority: carbonio.priority ?? 99,
            icon: carbonio.icon,
            attrKey: carbonio.attrKey ?? '',
            entryPoint: packageJson.name,
          };
          return manifest;
        }
      } catch {
        // Skip if package.json cannot be read
      }
      return null;
    })
    .filter((app): app is AppManifest => app !== null)
    .sort((a, b) => a.priority - b.priority);
}

/**
 * Generate state objects for apps and appContexts
 * @param apps - Array of app manifests
 * @returns Object string representation for use in generated code
 */
function buildStateObjects(apps: Array<AppManifest>): { apps: string; appContexts: string } {
  const appsObject = apps.reduce(
    (acc, app) => ({
      ...acc,
      [app.name]: {
        description: '',
        name: app.name,
        priority: app.priority,
        type: 'carbonioAdmin',
        attrKey: app.attrKey,
        icon: app.icon,
        display: app.displayName,
        js_entrypoint: app.entryPoint,
      },
    }),
    {},
  );
  const appContextsObject = apps.reduce((acc, app) => ({ ...acc, [app.name]: {} }), {});

  return {
    apps: JSON.stringify(appsObject),
    appContexts: JSON.stringify(appContextsObject),
  };
}

/**
 * Generate the loadAllApps function code
 * @param apps - Array of app manifests
 * @returns Generated function code string
 */
function generateLoadAllAppsCode(apps: Array<AppManifest>): string {
  const { apps: appsStr, appContexts: appContextsStr } = buildStateObjects(apps);

  const appImports = apps.map(
    (app) =>
      `try {
    const module${apps.indexOf(app)} = await import('${app.packageName}');
    const Component = module${apps.indexOf(app)}.default;
    useAppStore.setState((state) => ({
      entryPoints: {
        ...state.entryPoints,
        ['${app.name}']: Component
      }
    }));
    appContextMap.set('${app.packageName}', APP_REGISTRY.find((a) => a.packageName === '${
        app.packageName
      }'));
    console.info('%c loaded ${
      app.name
    }', 'color: white; background: #539507;padding: 4px 8px 2px 4px; font-family: sans-serif; border-radius: 12px; width: 100%');
  } catch (error) {
    console.error('Failed to load app ${app.name}:', error);
  }`,
  );

  return `export const APP_REGISTRY = ${JSON.stringify(apps, null, '\t')};

export async function loadAllApps(useAppStore, appContextMap) {
  useAppStore.setState((state) => ({
    apps: { ...${appsStr} },
    appContexts: { ...${appContextsStr} }
  }));

  ${appImports.join('\n\n  ')}
}
`;
}

/**
 * Vite plugin to generate app registry module
 * @returns Vite plugin
 */
export function appRegistryPlugin(): Plugin {
  const virtualModuleId = 'virtual:app-registry';
  const resolvedVirtualModuleId = '\0' + virtualModuleId;

  return {
    name: 'app-registry',
    resolveId(id: string) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },
    load(id: string) {
      if (id === resolvedVirtualModuleId) {
        const apps = scanAppsDir();
        const functionCode = generateLoadAllAppsCode(apps);

        return `/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Auto-generated by app-registry Vite plugin
 */

${functionCode}
`;
      }
    },
  };
}
